const products = [
  {
    id: "1",
    name: "A Bittersweet Life",
    image: "https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/35/82/47/18612040.jpg",
    casting: "Lee Byung-hun, Shin Min-a",
    description:
      "Un chef de gang suspecte sa petite amie Hee Su d'avoir une liaison avec un autre homme. Il demande à son bras droit, Sun Woo, de suivre Hee Su et de l'éliminer s'il la surprend en galante compagnie.",
    category: "Thriller",
    price: "15€50",
    countInStock: "3",
    rating: "2.5",
    numReview: "2",
  },
  {
    id: "2",
    name: "Painted Faces",
    image: "https://media.senscritique.com/media/000020318105/300/painted_faces.jpg",
    casting: "Sammo Hung",
    description:
      "Le film retrace l'histoire de l'Académie d'étude du théâtre chinois (中国戏剧研究学院, en anglais Peking Opera School), l'école hongkongaise dirigée par Maître Yu (joué par Sammo Hung, qui a été son élève à partir de 1959). Son enseignement était renommé pour être dur, et les coups de bâtons y étaient fréquents.",
    category: "Drame",
    price: "25€00",
    countInStock: "4",
    rating: "4.5",
    numReview: "10",
  },
  {
    id: "3",
    name: "City On Fire",
    image: "https://media.senscritique.com/media/000019091857/325/City_on_Fire.jpg",
    casting: "Chow Yun-fat, Danny Lee",
    description:
      "Un policier inflitre un gang de cambrioleurs prêts à organiser le casse d'une bijouterie.",
    category: "Policier",
    price: "15€50",
    countInStock: "3",
    rating: "3.8",
    numReview: "10",
  },
  {
    id: "4",
    name: "School On Fire",
    image: "https://media.senscritique.com/media/000019091971/300/school_on_fire.jpg",
    casting: "Roy Chung",
    description:
      "Dans les années 90, à Hong-Kong. Des élèves d'une école sont harcelés par les chefs de triades. Deux policiers vont essayer de venir à bout de leurs méfaits, aidés par une des jeunes victimes, et un professeur à la morale de fer...",
    category: "Drame",
    price: "15€50",
    countInStock: "9",
    rating: "4.7",
    numReview: "20",
  },
  {
    id: "5",
    name: "A Toute Epreuve",
    image: "https://fr.web.img5.acsta.net/medias/nmedia/18/74/32/07/19253593.jpg",
    casting: "Chow Yuen-fat",
    description:
      "Hong-Kong 1997. Les Britanniques vont rendre dans quelques mois à la Chine populaire une ville corrompue par le crime. Alors que les policiers ont baissé les bras, un groupe d'inspecteurs, mené par Yuen, surnommé Tequila, décide de mettre fin a la suprématie des gangs.",
    category: "Action",
    price: "13€00",
    countInStock: "6",
    rating: "4.2",
    numReview: "20",
  },
  {
    id: "6",
    name: "Big Boss",
    image: "https://m.media-amazon.com/images/I/71wmrh75zcL._AC_SL1500_.jpg",
    casting: "Bruce Lee",
    description:
      "Un ouvrier venant de la campagne se révolte contre la milice engagée par son patron pour briser une grève.",
    category: "Kung-fu",
    price: "8€50",
    countInStock: "0",
    rating: "3.8",
    numReview: "20",
  },
  {
    id: "7",
    name: "J'ai rencontré Le Diable",
    image: "https://fr.web.img6.acsta.net/medias/nmedia/18/82/79/34/19637299.jpg",
    casting: "Park Hoon-chung",
    description:
      "Un agent secret recherche le serial killer qui a tué sa fiancée...",
    category: "Drame",
    price: "15€50",
    countInStock: "9",
    rating: "4.0",
    numReview: "20",
  },
  {
    id: "8",
    name: "Maniac",
    image: "https://p5.storage.canalblog.com/58/10/1349409/106661561.jpg",
    casting: "Joe Spinell",
    description:
      "Un psychopathe sème la mort en ville en scalpant ses victimes pour recréer sa mère abusive décédée plusieurs années auparavant.",
    category: "Horreur",
    price: "18€50",
    countInStock: "9",
    rating: "3.8",
    numReview: "20",
  },
  {
    id: "9",
    name: "L'au-delà",
    image: "https://www.horreur.net/sites/default/files/upload/audelacollector.jpg",
    casting: "Luci Fulci",
    description:
      "Une jeune femme hérite d'un hôtel dans la Nouvelle Orléans. Alors qu'elle entreprend des travaux de rénovation, des phénomènes étranges font de sa vie un véritable enfer.",
    category: "Drame",
    price: "15€50",
    countInStock: "9",
    rating: "4.7",
    numReview: "20",
  },
  {
    id: "10",
    name: "The Chaser",
    image: "https://m.media-amazon.com/images/M/MV5BY2ViOTU5MDQtZTRiZi00YjViLWFiY2ItOTRhNWYyN2ZiMzUyXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg",
    casting: "Yun-seok Kim, Jung-woo Ha",
    description:
      "Joong-ho, ancien flic devenu proxénète, reprend du service lorsqu'il se rend compte que ses filles disparaissent les unes après les autres. Très vite, il réalise qu'elles avaient toutes rencontré le même client, identifié par les derniers chiffres de son numéro de portable. Joong-ho se lance alors dans une chasse à l'homme, persuadé qu'il peut encore sauver Mi-jin, la dernière victime du tueur. ",
    category: "Drame",
    price: "15€50",
    countInStock: "9",
    rating: "4.2",
    numReview: "20",
  },
  {
    id: "11",
    name: "Memories Of Murder",
    image: "https://fr.web.img2.acsta.net/pictures/17/04/14/09/41/477957.jpg",
    casting: "Song Kang-Ho, Kim Sang-kyung",
    description:
      "En 1986, dans la province de Gyunggi, le corps d'une jeune femme violée puis assassinée est retrouvé dans la campagne. Deux mois plus tard, d'autres crimes similaires ont lieu. Dans un pays qui n'a jamais connu de telles atrocités, la rumeur d'actes commis par un serial killer grandit de jour en jour. Une unité spéciale de la police est ainsi créée dans la région afin de trouver rapidement le coupable. Elle est placée sous les ordres d'un policier local et d'un détective spécialement envoyé de Séoul à sa demande. Devant l'absence de preuves concrètes, les deux hommes sombrent peu à peu dans le doute... ",
    category: "Thriller",
    price: "18€50",
    countInStock: "9",
    rating: "4.7",
    numReview: "20",
  },
  {
    id: "12",
    name: "Mother",
    image: "https://fr.web.img6.acsta.net/c_310_420/medias/nmedia/18/70/39/68/19219777.jpg",
    casting: "Song Kang-Ho, Kim Sang-kyung",
    description:
      "En 1986, dans la province de Gyunggi, le corps d'une jeune femme violée puis assassinée est retrouvé dans la campagne. Deux mois plus tard, d'autres crimes similaires ont lieu. Dans un pays qui n'a jamais connu de telles atrocités, la rumeur d'actes commis par un serial killer grandit de jour en jour. Une unité spéciale de la police est ainsi créée dans la région afin de trouver rapidement le coupable. Elle est placée sous les ordres d'un policier local et d'un détective spécialement envoyé de Séoul à sa demande. Devant l'absence de preuves concrètes, les deux hommes sombrent peu à peu dans le doute... ",
    category: "Drame",
    price: "12€50",
    countInStock: "9",
    rating: "4.0",
    numReview: "20",
  },
  {
    id: "13",
    name: "Il Etait Une Fois En Chine",
    image: "https://fr.web.img6.acsta.net/pictures/210/446/21044672_20130927125215421.jpg",
    casting: "Jet Li",
    description:
      "A la fin du XIXe siècle à Fa Shan, en Chine du Sud. Tandis que les puissances coloniales européennes et américaines s'y affrontent pour le contrôle du commerce maritime, les premiers signes d'occidentalisation commencent à percer dans la société chinoise. Dans ce climat politique tendu, Wong Fei-hung, docteur en médecine chinoise, maître de kung-fu et chef instructeur de l'armée du Dragon noir, est chargé par le commandant Lau de maintenir l'ordre durant les guerres qui éloignent ses troupes de la région, afin de sauvegarder ce qui reste de paix et de stabilité. ",
    category: "Action",
    price: "19€50",
    countInStock: "9",
    rating: "4.5",
    numReview: "20",
  },
  {
    id: "14",
    name: "Blood Island",
    image: "https://fr.web.img4.acsta.net/medias/nmedia/18/83/05/15/19707874.jpg",
    casting: "Song Kang-Ho, Kim Sang-kyung",
    description:
      "Hae-won est une jolie trentenaire célibataire. Contrainte à partir en congés, elle se rend à Moodo, une petite île sur laquelle elle passait ses vacances étant plus jeune. Elle y retrouve Bok-nam, son amie d’enfance, soumise à la volonté tyrannique de ses habitants et à des humiliations quotidiennes. ",
    category: "Horreur",
    price: "12€50",
    countInStock: "9",
    rating: "4.0",
    numReview: "20",
  },
 
];

export default products;
